import img1 from '../assets/img/pizza.jpeg';

const pizzas = [
  {
    name: 'Чизбургер-пицца',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
    meat: true,
    vegan: false,
  },
  {
    name: 'Пицца 1',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
    grille: true,
  },
  {
    name: 'Пицца 2',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
    meat: true,
    vegan: false,
  },
  {
    name: 'Пицца 3',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
  },
  {
    name: 'Пицца 4',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
  },
  {
    name: 'Пицца 5',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
    meat: true,
    vegan: false,
    grille: true,
  },
  {
    name: 'Пицца 6',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
  },
  {
    name: 'Пицца 7',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
    grille: true,
  },
  {
    name: 'Пицца 8',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
    grille: true,
  },
  {
    name: 'Пицца 9',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
    spicy: true,
  },
  {
    name: 'Пицца 10',
    img: img1,
    width: ['thin', 'traditional'],
    sizes: [26, 30, 40],
    price: [395],
    spicy: true,
  },
];

export default pizzas;
